export const RISK_LEVELS = ['LOW', 'MODERATE', 'HIGH'] as const
export const PLANS = ['FREE', 'FARMER', 'PROFESSIONAL', 'ENTERPRISE'] as const
export const PLAN_LABELS: Record<string, string> = {
  FREE: 'Free',
  FARMER: 'Farmer',
  PROFESSIONAL: 'Professional',
  ENTERPRISE: 'Enterprise',
}

export const PLANTS = [
  { id: 1, name: 'alo Vera' },
  { id: 2, name: 'Apple leaf' },
  { id: 3, name: 'Ashwagandha' },
  { id: 4, name: 'Banana' },
  { id: 5, name: 'Bell_pepper leaf' },
  { id: 6, name: 'Blueberry leaf' },
  { id: 7, name: 'Calendula' },
  { id: 8, name: 'Chamomile' },
  { id: 9, name: 'Cherry leaf' },
  { id: 10, name: 'Cinnamon' },
  { id: 11, name: 'Clove' },
  { id: 12, name: 'Corn Gray leaf spot' },
  { id: 13, name: 'Corn leaf blight' },
  { id: 14, name: 'Dandelion' },
  { id: 15, name: 'Echinacea' },
  { id: 16, name: 'eucalyptus' },
  { id: 17, name: 'Fenugreek' },
  { id: 18, name: 'Garlic' },
  { id: 19, name: 'Ginger' },
  { id: 20, name: 'Ginkgo' },
  { id: 21, name: 'Ginseng' },
  { id: 22, name: 'grape leaf' },
  { id: 23, name: 'Holy_Basil' },
  { id: 24, name: 'Lavender' },
  { id: 25, name: 'Licorice' },
  { id: 26, name: 'Mango' },
  { id: 27, name: 'Moringa' },
  { id: 28, name: 'Neem' },
  { id: 29, name: 'Papaya' },
  { id: 30, name: 'Peach leaf' },
  { id: 31, name: 'peppermint' },
  { id: 32, name: 'pigeon' },
  { id: 33, name: 'Pigeon_Pea' },
  { id: 34, name: 'Potato leaf early blight' },
  { id: 35, name: 'Raspberry leaf' },
  { id: 36, name: 'Rosemary' },
  { id: 37, name: 'Saw_Palmetto' },
  { id: 38, name: 'Soyabean leaf' },
  { id: 39, name: 'St._John_s_Wort' },
  { id: 40, name: 'Strawberry leaf' },
  { id: 41, name: 'Sugarcane' },
  { id: 42, name: 'Tea_Tree' },
  { id: 43, name: 'Tomato leaf' },
  { id: 44, name: 'Tulsi' },
  { id: 45, name: 'turmeric' },
  { id: 46, name: 'Valerian' },
]

export const CROPS = PLANTS

export const SOIL_TYPES = ['Black soil', 'Red soil', 'Alluvial', 'Sandy', 'Clay', 'Loamy', 'Unknown']
export const IRRIGATION_TYPES = ['Rainfed', 'Drip', 'Sprinkler', 'Flood', 'Other', 'Unknown']
export const API_ENDPOINTS = {
  login: '/auth/login',
  register: '/auth/register',
  me: '/auth/me',
  farms: '/farms',
  soil: '/farms/{id}/soil',
  weather: '/farms/{id}/weather',
  forecast: '/farms/{id}/weather/forecast',
  satellite: '/farms/{id}/satellite',
  analyze: '/farms/{id}/analyze',
  health: '/farms/{id}/health',
  risks: '/farms/{id}/risks',
  recommendations: '/farms/{id}/recommendations',
  alerts: '/alerts',
  reports: '/farms/{id}/reports',
  assistant: '/assistant',
  subscriptions: '/subscriptions',
}
